build:
  unit_tests:
    image: harvardnlp/opennmt:8.0
    commands:
      - luarocks install luacheck
      - luacheck *lua onmt/

  integration_tests:
    image: node
    environment:
      PASSWORD: $$PASSWORD
    commands:
      - npm run integration
    when:
      event: push
